name: Tests

on:
  merge_group:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: "always"
  # For faster CI
  RUST_LOG: "off"
  # This ensures make commands don't do fixes
  NO_FIX: "true"
  TARGET_FILE: target/wasm32-wasip1/release/node_globals_inject.wasm

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: "${{ github.event_name == 'pull_request' }}"

jobs:
  cargo-fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    env:
      RUST_LOG: "0"
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: "Cargo Fmt"
        run: make fmt

  cargo-clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: "Cargo Clippy"
        run: make clippy

  cargo-deny:
    name: Check license of dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@0.14.15

      - name: Check licenses
        run: |
          make licenses-check

      - name: Check Bans
        run: |
          make bans-check

  cargo-check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      # Ensure that all components are compilable.
      - name: Run cargo check for all targets
        run: cargo check --all --all-targets

  cargo-test:
    name: Cargo Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasip1

      - name: Run cargo test
        run: |
          make test

  cargo-build:
    name: Cargo Build
    runs-on: ubuntu-latest
    outputs:
      target-cache-key: ${{ steps.cache-target.outputs.cacheKey }}
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasip1

      - name: Run cargo test
        run: |
          make build

      - name: Cache Build Output
        uses: actions/cache/save@v4
        with:
          path: ${{ env.TARGET_FILE }}
          key: target-build-${{ hashFiles( env.TARGET_FILE ) }}
          enableCrossOsArchive: true
      
      - name: Output Key
        id: cache-target
        run: |
          echo "cacheKey=target-build-${{ hashFiles( env.TARGET_FILE ) }}" >> "$GITHUB_OUTPUT"

  node-int-test:
    name: Node Integration Test
    needs:
      - cargo-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - '18.x'
          - '20.x'
          - '22.x'
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasip1

      - name: Restore Target Build
        id: target-build-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.TARGET_FILE }}
          key: ${{ needs.cargo-build.outputs.target-cache-key }}
          enableCrossOsArchive: true

      - name: Run node-int-test
        env:
          NO_BUILD: ${{ (steps.target-build-restore.outputs.cache-hit && 'true') || '' }}
        shell: bash
        run: |
          corepack enable
          make node-int-test

  done:
    needs:
      - cargo-fmt
      - cargo-clippy
      - cargo-deny
      - cargo-check
      - cargo-test
      - node-int-test
    runs-on: ubuntu-latest
    name: Done
    steps:
      - run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}